[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    windows_only: mark a test as running only on Windows operating systems
    linux_only: mark a test as running only on Linux operating systems
    macos_only: mark a test as running only on macOS operating systems
    cross_platform: mark a test as valid across Windows, Linux, and macOS
