"""
PPTX Presentation Generation MCP Server (Stdio JSON-RPC 2.0)
Wraps python-pptx for presentation creation with B.40 verification.
"""

import json
from pathlib import Path
import sys
from typing import Any, Dict, List, Optional

# Ensure UTF-8 I/O on Windows when available
if sys.platform == "win32":
    for stream in (sys.stdin, sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8")
            except Exception:
                pass


def log_debug(msg: str) -> None:
    try:
        sys.stderr.write(f"[MCP PPTX Server] {msg}\n")
        sys.stderr.flush()
    except Exception:
        pass


def generate_pptx(file_path: str, title: str, slides: Optional[List[Dict[str, str]]] = None, content: str = "") -> Dict[str, Any]:
    """Generate a formatted PPTX presentation using python-pptx."""
    path = Path(file_path).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)

    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt

        prs = Presentation()

        # Slide 1: Title Slide (layout index 0)
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]

        title_shape.text = title
        subtitle_shape.text = "Generated by Windows AI Agent Multi-Agent Engine"

        # Content Slide layout (layout index 1)
        bullet_slide_layout = prs.slide_layouts[1]

        # Explicit structured slides if provided
        if slides:
            for s in slides:
                s_title = s.get("title", s.get("heading", "Topic"))
                s_body = s.get("body", s.get("content", ""))
                c_slide = prs.slides.add_slide(bullet_slide_layout)
                c_slide.shapes.title.text = s_title
                tf = c_slide.placeholders[1].text_frame
                tf.clear()
                first = True
                for line in s_body.split("\n"):
                    clean = line.strip().lstrip("-*• ")
                    if clean:
                        if first:
                            p = tf.paragraphs[0]
                            p.text = clean
                            first = False
                        else:
                            p = tf.add_paragraph()
                            p.text = clean

        # Markdown parsing if content provided and no explicit slides
        if content and not slides:
            current_title = "Overview"
            current_bullets: List[str] = []

            for line in content.split("\n"):
                clean = line.strip()
                if clean.startswith("# ") or clean.startswith("## "):
                    if current_bullets:
                        c_slide = prs.slides.add_slide(bullet_slide_layout)
                        c_slide.shapes.title.text = current_title
                        tf = c_slide.placeholders[1].text_frame
                        tf.clear()
                        for idx, b in enumerate(current_bullets):
                            p = tf.paragraphs[0] if idx == 0 else tf.add_paragraph()
                            p.text = b
                        current_bullets = []
                    current_title = clean.lstrip("#").strip()
                elif clean:
                    current_bullets.append(clean.lstrip("-*• "))

            if current_bullets:
                c_slide = prs.slides.add_slide(bullet_slide_layout)
                c_slide.shapes.title.text = current_title
                tf = c_slide.placeholders[1].text_frame
                tf.clear()
                for idx, b in enumerate(current_bullets):
                    p = tf.paragraphs[0] if idx == 0 else tf.add_paragraph()
                    p.text = b

        prs.save(str(path))

    except Exception as e:
        log_debug(f"python-pptx generation error: {e}")
        raise RuntimeError(f"Failed to generate PPTX presentation: {e}")

    # Post-action verification (B.40)
    if not path.exists():
        raise FileNotFoundError(f"Verification Failed: PPTX file '{path}' was not written.")

    size_bytes = path.stat().st_size
    if size_bytes == 0:
        raise IOError(f"Verification Failed: PPTX file '{path}' is 0 bytes.")

    return {
        "file_path": str(path),
        "size_bytes": size_bytes,
        "title": title,
        "status": "success",
        "verified_success": True,
    }


def handle_request(req: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    method = req.get("method")
    req_id = req.get("id")

    if method == "initialize":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {}},
                "serverInfo": {
                    "name": "pptx_presentation_server",
                    "version": "1.0.0",
                },
            },
        }

    elif method == "notifications/initialized":
        return None

    elif method == "tools/list":
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "tools": [
                    {
                        "name": "create_pptx",
                        "description": "Create a formatted, verified PPTX PowerPoint presentation with slides, titles, and bullet points.",
                        "inputSchema": {
                            "type": "object",
                            "properties": {
                                "file_path": {
                                    "type": "string",
                                    "description": "Absolute destination path for the generated PPTX file",
                                },
                                "title": {
                                    "type": "string",
                                    "description": "Presentation title heading",
                                },
                                "content": {
                                    "type": "string",
                                    "description": "Markdown text with headings and bullets to convert into slides",
                                },
                                "slides": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "title": {"type": "string"},
                                            "body": {"type": "string"},
                                        },
                                    },
                                    "description": "Optional list of structured slide objects",
                                },
                            },
                            "required": ["file_path", "title"],
                        },
                    }
                ]
            },
        }

    elif method == "tools/call":
        params = req.get("params", {})
        tool_name = params.get("name")
        arguments = params.get("arguments", {})

        if tool_name == "create_pptx":
            file_path = arguments.get("file_path", "")
            title = arguments.get("title", "Presentation")
            content = arguments.get("content", "")
            slides = arguments.get("slides")

            try:
                res = generate_pptx(file_path, title, slides=slides, content=content)
                return {
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": {
                        "content": [
                            {
                                "type": "text",
                                "text": json.dumps(res, indent=2),
                            }
                        ],
                        "isError": False,
                    },
                }
            except Exception as e:
                return {
                    "jsonrpc": "2.0",
                    "id": req_id,
                    "result": {
                        "content": [{"type": "text", "text": f"Error generating PPTX: {e}"}],
                        "isError": True,
                    },
                }

        else:
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "error": {
                    "code": -32601,
                    "message": f"Unknown tool '{tool_name}'",
                },
            }

    else:
        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "error": {
                "code": -32601,
                "message": f"Method '{method}' not found",
            },
        }


def main():
    log_debug("PPTX Presentation MCP Server started over stdio.")
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
            resp = handle_request(req)
            if resp is not None:
                sys.stdout.write(json.dumps(resp) + "\n")
                sys.stdout.flush()
        except Exception as e:
            log_debug(f"Error handling request: {e}")
            err_resp = {
                "jsonrpc": "2.0",
                "id": None,
                "error": {"code": -32700, "message": f"Parse error: {e}"},
            }
            sys.stdout.write(json.dumps(err_resp) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
